### PR TITLE
MacOS layout bundle

### PR DESCRIPTION
**Pull request by eugeny-dementev**
- Layout made with Ukelele
- All keys preserve their macos mappings for shift and alt layers including Alt, Alt+Shift, Alt+Control to give expected macos experience
- Layout marked as English so it's present in English layouts list inside Keyboard Setting
- Add README.md macos setup section

Unfortunately I didn't found a way to mark it as fully English compatible to make it possible to easily remove default English layout so have to use hacks to make Engrammer the only English layout if it's needed. From what I can tell it might be not even possible to do for custom layouts to be treated equal to default layouts

### CODE REVIEW

**Comment by sunaku** [comment]
Thank you! :pray:  I've asked the community to help test this since I don't use macOS myself :sweat_smile:, so please stand by. :hourglass_flowing_sand:

**Comment by bwknight877** [comment]
verification:

copying `Engrammer.bundle` to `~/Library/Keyboard Layouts/` works as expected:
image

After logging out and back in, the `Engrammer` keyboard layout shows up under the `English` language as expected when you try to add a keyboard input source:
image

If you enable `Show Input menu in menu bar` the layout also shows up as expected:
image

The `Engrammer` layout in the Keyboard Viewer in macos looks as expected with no modifiers:
image

Also the `Engrammer` layout view with the Shift key pressed:
image

**Comment by bwknight877** [comment]
edit: disregard this based on my comment below

with the above screenshots, @sunaku do you have any comments about the translation of your engrammer layout to the macbook keyboard?

@eugeny-dementev I might consider leaving the `+=` key in place, and replacing the default macbook `_-` key with `\|` so it is to the right of `0`, and shifting the default `[{` and `}]` positions over one key to the right of their original under the `delete` key

its not as easy to translate engrammer to the macbook keyboard exactly due to the staggered key layout and a few less keys in some spots

base US English MacBook keyboard for reference:
image

**Comment by bwknight877** [comment]
also FWIW, I tried doing this exact same thing last night, and posted in `#glorious-engrammer` in the glove80 discord
https://discord.com/channels/877392805654306816/1193051200938049546/1214757184303407194

**Comment by eugeny-dementev** [comment]
@bwknight877 Thank you for the review and confirmation that layout is working as intended. 

While I do understand what you suggesting regarding tossing [ and ] keys to different places, I do not think it's a good idea to do so. It's a minor change that suitable for particular keyboard configuration and can be achieved by tools like Karabiner or KMonad if needed.

I think consistency is more important. To have the same behaviour of layouts present in that repo for all supported OS. Otherwise if someone is having dualboot for linux and macos for example, they'll have different experience between their environments while it's natural to expect it to be the same

**Comment by bwknight877** [comment]
@eugeny-dementev you're totally right here, consistency is important

I've got a glove80 and I've been too hyper focused on this layout: https://sunaku.github.io/moergo-glove80-keyboard.html#layers

and this one: https://sunaku.github.io/engram-keyboard-layout.html#engrammer

I totally missed that _this repo_ has the layout that you're replicating! 🤦🏻 
https://github.com/sunaku/engrammer?tab=readme-ov-file#engrammer---arnos-engram-layout-for-programmers

And on that note, this PR looks good to me, :shipit:

**Review by bwknight877 — APPROVED** [review]

**Comment by eugeny-dementev** [comment]
@sunaku Please take a look and merge if all okay for you

**Comment by sunaku** [comment]
Merged, thank you all! :pray:

**Pull request merged**
